export const data = [
  {
    id:1,
    src: "https://m.media-amazon.com/images/I/41IcuNkyrdL._SX300_SY300_QL70_FMwebp_.jpg",
    alt: "Product Image 1",
    product: "Mobile",
    price: "$300",
    desc: "Samsung M04",
    Quantity:1,
  },
  {
    id:2,
    src: "https://m.media-amazon.com/images/I/718XDEWTPIL._UL1500_.jpg",
    alt: "Product Image 2",
    product: "Watch",
    price: "$120",
    desc: "Redux Watch",
    Quantity:1,
  },
  {
    id:3,
    src: "https://m.media-amazon.com/images/I/51UhwaQXCpL._SX679_.jpg",
    alt: "Product Image 3",
    product: "Earphones",
    price: "$70",
    desc: "Boat earphones",
    Quantity:1,
  },
  {
    id:4,
    src: "https://m.media-amazon.com/images/I/51tS-cfYoXL._SX679_.jpg",
    alt: "Product Image 4",
    product: "Charger",
    price: "$50",
    desc: "Apple charger",
    Quantity:1,
  },
  {
    id:5,
    src: "https://m.media-amazon.com/images/I/51sZaNaWzZL._SX300_SY300_QL70_FMwebp_.jpg",
    alt: "Product Image 5",
    product: "Laptop",
    price: "$1000",
    desc: "HP Laptop",
    Quantity:1,
  },
  {
    id:6,
    src: "https://m.media-amazon.com/images/I/81WtQ64-SOL._SX522_.jpg",
    alt: "Product Image 6",
    product: "Camera",
    price: "$500",
    desc: "Nikon Camera",
    Quantity:1,
  },
  {
    id:7,
    src: "https://m.media-amazon.com/images/I/71S-WpFnW+L._SL1500_.jpg",
    alt: "Product Image 7",
    product: "TV",
    price: "$500",
    desc: "Television",
    Quantity:1,
  },
  {
    id:8,
    src: "https://m.media-amazon.com/images/I/71GU85VOpnL._SX522_.jpg",
    alt: "Product Image 8",
    product: "Projector",
    price: "$500",
    desc: "Projector",
    Quantity:1,
  },
  {
    id:9,
    src: "https://m.media-amazon.com/images/I/31NVItwqOnL._SX300_SY300_QL70_FMwebp_.jpg",
    alt: "Product Image 9",
    product: "Printer",
    price: "$500",
    desc: "Hourse Hold Printer",
    Quantity:1,
  },
];