const ProductList = [
  {
    id:1,
    src:"https://m.media-amazon.com/images/I/51vHAEYKeWL._SX300_SY300_QL70_FMwebp_.jpg",
    img1:"https://m.media-amazon.com/images/I/71rrzNqSWQL._SY355_.jpg ",
    img2:"https://m.media-amazon.com/images/I/71APxf0yOhL._SY355_.jpg",
    img3:"https://m.media-amazon.com/images/I/61cSMrIDRfL._SY355_.jpg",
    img4:"https://m.media-amazon.com/images/I/71jdbKDNmBL._SY355_.jpg",
    alt: "Product Image 1",
    product: "Smart Watch",
    price: "₹2499",
    // desc: "Samsung M04",
    category:"electronics",
    prod_info:"Fire-Boltt Gladiator 1.96 Biggest Display Smart Watch with Bluetooth Calling, Voice Assistant &123 Sports Modes, 8 Unique UI Interactions SpO2, 24/7 Heart Rate Tracking ,Rs 100 Off on UPI"
  },
  {
    id:2,
    src: "https://m.media-amazon.com/images/I/71Q5Wo8yyOL._SX450_.jpg",
    img1:"https://m.media-amazon.com/images/I/61b4CEb1iBL._SY450_.jpg",
    img2:"https://m.media-amazon.com/images/I/61jol8EuIvL._SY450_.jpg",
    img3:"https://m.media-amazon.com/images/I/61jVzxqIR4L._SY450_.jpg",
    img4:"https://m.media-amazon.com/images/I/51N9L-ODmGL._SL1000_.jpg",
    alt: "Product Image 2",
    product: "Touchscreen Laptop",
    price: "₹1,04,990",
    // desc: "Redux Watch",
    category:"electronics",
    prod_info:"Lenovo Yoga 7 11th Gen Intel Core i7 14 (35cm) Full HD IPS 2-in-1 Touchscreen Laptop (16GB/512GB SSD/Windows 10/MS Office 2019/Lenovo Digital Pen/Slate Grey/Aluminium Surface/1.43Kg), 82BH00E0INLenovo Yoga 7 11th Gen Intel Core i7 14 (35cm) Full HD IPS 2-in-1 Touchscreen Laptop (16GB/512GB SSD/Windows 10/MS Office 2019/Lenovo Digital Pen/Slate Grey/Aluminium Surface/1.43Kg), 82BH00E0IN"
  },
  {
    id:3,
    src: "https://rukminim1.flixcart.com/image/416/416/xif0q/mobile/g/q/q/-original-imaggcz6fyt9yayh.jpeg?q=70",
    img1:"https://rukminim1.flixcart.com/image/416/416/xif0q/mobile/o/a/i/-original-imaggcz6dgz3zkga.jpeg?q=70",
    img2:"https://rukminim1.flixcart.com/image/416/416/xif0q/mobile/k/0/h/-original-imaggcz6bnxmmfjm.jpeg?q=70",
    img3:"https://rukminim1.flixcart.com/image/416/416/xif0q/mobile/n/p/l/-original-imaggcz6w65htnup.jpeg?q=70",
    img4:"https://rukminim1.flixcart.com/image/416/416/xif0q/mobile/q/u/y/-original-imaggcz6muuhhpbu.jpeg?q=70",
    alt: "Product Image 3",
    product: "Mobile",
    price: "₹23,950",
    // desc: "Boat earphones",
    category:"electronics",
    prod_info:"Mi 11X (Cosmic Black, 128 GB)  (6 GB RAM)"
  },
  {
    id:4,
    src: "https://rukminim1.flixcart.com/image/416/416/xif0q/television/5/m/s/-original-imagz88djd2dktwz.jpeg?q=70",
    img1:"https://rukminim1.flixcart.com/image/416/416/xif0q/television/1/c/d/ar65ar2851qd-acer-original-imagnz7nfzaxwvam.jpeg?q=70",
    img2:"https://rukminim1.flixcart.com/image/416/416/xif0q/television/w/l/j/ar65ar2851qd-acer-original-imagnz7nvkdhd6cg.jpeg?q=70",
    img3:"https://rukminim1.flixcart.com/image/416/416/xif0q/television/n/2/w/ar65ar2851qd-acer-original-imagnz7ncsmesrfm.jpeg?q=70",
    img4:"https://rukminim1.flixcart.com/image/416/416/xif0q/television/d/0/2/ar65ar2851qd-acer-original-imagnz7nhhhcyfy4.jpeg?q=70",
    alt: "Product Image 4",
    product: "Smart Android TV ",
    price: "₹89,999",
    // desc: "Apple charger",
    category:"electronics",
    prod_info:"acer 165 cm (65 inch) QLED Ultra HD (4K) Smart Android TV With Super Anti Glare Display, Motion Sensor, Far Field Mic  (AR65AR2851QD)"
  },
  {
    id:5,
    src: "https://rukminim1.flixcart.com/image/416/416/xif0q/computer/7/3/l/-original-imagha3pvvc2xuz2.jpeg?q=70",
    img1:"https://rukminim1.flixcart.com/image/416/416/xif0q/computer/x/i/l/-original-imagh2jxzahy4hhz.jpeg?q=70",
    img2:"https://rukminim1.flixcart.com/image/416/416/xif0q/computer/m/v/4/-original-imagh2jxaqzgzecc.jpeg?q=70",
    img3:"https://rukminim1.flixcart.com/image/416/416/xif0q/computer/x/v/a/bravo-15-b5dd-notebook-msi-original-imaggmy3zbn6kf5g.jpeg?q=70",
    img4:"https://rukminim1.flixcart.com/image/416/416/xif0q/computer/y/s/8/bravo-15-b5dd-notebook-msi-original-imaggmy3ugujpfhs.jpeg?q=70",
    alt: "Product Image 5",
    product: "Laptop",
    price: "₹47,990",
    // desc: "HP Laptop",
    category:"electronics",
    prod_info:"MSI Bravo 15 Ryzen 5 Hexa Core AMD R5-5600H - (8 GB/512 GB SSD/Windows 11 Home/4 GB Graphics/AMD Radeon RX 5500M/144 Hz) Bravo 15 B5DD-410IN Gaming Laptop  (15.6 inch, Black, 2.35 kg kg)",
  },
  {
    id:6,
    src: "https://rukminim1.flixcart.com/image/416/416/kk01pjk0/dslr-camera/f/v/o/eos-1500d-canon-original-imafzfugydh2mjgf.jpeg?q=70",
    img1:"https://rukminim1.flixcart.com/image/416/416/kk01pjk0/dslr-camera/f/v/o/eos-1500d-canon-original-imafzfugydh2mjgf.jpeg?q=70",
    img2:"https://rukminim1.flixcart.com/image/416/416/kk01pjk0/dslr-camera/n/t/q/eos-1500d-canon-original-imafzfugrcz6e3xy.jpeg?q=70",
    img3:"https://rukminim1.flixcart.com/image/416/416/kk01pjk0/dslr-camera/w/f/q/eos-1500d-canon-original-imafzfugm7yaxf6b.jpeg?q=70",
    img4:"https://rukminim1.flixcart.com/image/416/416/kk01pjk0/dslr-camera/n/t/q/eos-1500d-canon-original-imafzfugrcz6e3xy.jpeg?q=70",
    alt: "Product Image 6",
    product: "Camera",
    price: "₹36,990",
    // desc: "Nikon Camera",
    category:"electronics",
    prod_info:"Canon EOS 1500D DSLR Camera Body+ 18-55 mm IS II Lens  (Black)"
  },
  {
    id:7,
    src: "https://rukminim1.flixcart.com/image/416/416/kmwcuq80/headphone/h/d/k/e21-truke-original-imagfp8fbsz6qbgx.jpeg?q=70",
    img1:"https://rukminim1.flixcart.com/image/416/416/knj7wcw0/headphone/i/x/2/e21-truke-original-imag26wkd4ehyzug.jpeg?q=70",
    img2:"https://rukminim1.flixcart.com/image/416/416/knj7wcw0/headphone/9/a/e/e21-truke-original-imag26wkdfw8tfxq.jpeg?q=70",
    img3:"https://rukminim1.flixcart.com/image/416/416/knj7wcw0/headphone/s/m/t/e21-truke-original-imag26wkpzshkzwu.jpeg?q=70",
    img4:"https://rukminim1.flixcart.com/image/416/416/knj7wcw0/headphone/t/e/k/e21-truke-original-imag26wkjqdebwyd.jpeg?q=70",
    alt: "Product Image 7",
    product: "Bluetooth Headset",
    price: "₹1,099",
    // desc: "Television",
    category:"electronics",
    prod_info:"truke Buds Q1 with 30H Playtime, Quad Mic ENC, Game Mode, 10mm driver, AAC codec Bluetooth Headset  (Black, True Wireless)"
  },
  {
    id:8,
    src: "https://rukminim1.flixcart.com/image/416/416/l3khsi80/projector/z/h/4/-original-imagenqrzfcgwqk7.jpeg?q=70",
    img1:"https://rukminim1.flixcart.com/image/416/416/l3khsi80/projector/l/z/v/-original-imagenqr4tszjtfa.jpeg?q=70",
    img2:"https://rukminim1.flixcart.com/image/416/416/l3khsi80/projector/q/m/f/-original-imagenqr2ubzcer7.jpeg?q=70",
    img3:"https://rukminim1.flixcart.com/image/416/416/l3khsi80/projector/r/m/c/-original-imagenqrysrjsrzh.jpeg?q=70",
    img4:"https://rukminim1.flixcart.com/image/416/416/l3khsi80/projector/d/q/g/-original-imagenqrc4jygk9j.jpeg?q=70",
    alt: "Product Image 8",
    product: "Projector",
    price: "₹6,500",
    // desc: "Projector",
    category:"electronics",
    prod_info:"ZEBRONICS ZEB-PIXAPLAY 11 LED with FHD1080p support, built in speaker,Dual power input (1500 lm) Portable Projector  (White)",
  },
  {
    id:9,
    src: "https://rukminim1.flixcart.com/image/416/416/xif0q/battery-charger/k/w/b/dart-flash-wrap-with-typec-cable-n5t3-fast-charging-for-all-original-imagn55dsjnnzfpt.jpeg?q=70",
    img1:"https://rukminim1.flixcart.com/image/416/416/xif0q/battery-charger/q/t/h/65w-super-vooc-flash-wrap-dart-fast-charge-for-oneplus-nord-2t-original-imag9ghfhzzyydge.jpeg?q=70",
    img2:"https://rukminim1.flixcart.com/image/416/416/xif0q/data-cable/usb-type-c-cable/d/p/w/65w-6-5a-super-fast-charging-cable-type-c-support-supercharger-original-imagh8mzarznw3kh.jpeg?q=70",
    img3:"https://rukminim1.flixcart.com/image/416/416/kpedle80/battery-charger/q/k/q/30w-5v-4a-vooc-flash-charging-adapter-compatible-for-realme-oppo-original-imag3ndb4ndgfjcf.jpeg?q=70",
    img4:"https://rukminim1.flixcart.com/image/416/416/xif0q/battery-charger/k/w/b/dart-flash-wrap-with-typec-cable-n5t3-fast-charging-for-all-original-imagn55dsjnnzfpt.jpeg?q=70",
    alt: "Product Image 9",
    product: "Charger",
    price: "₹494",
    // desc: "Hourse Hold Printer",
    category:"electronics",
  },
  {
    id:10,
    src: "https://rukminim1.flixcart.com/image/416/416/ktyp8cw0/fmcg-combo/v/9/k/gold-dry-fruits-gift-box-6-eighty7-original-imag7684zfdbrw2r.jpeg?q=70",
    img1:"https://rukminim1.flixcart.com/image/416/416/l0bbonk0/fmcg-combo/g/a/t/classic-dry-fruits-almonds-cashews-raisins-and-cranberries-6-original-imagc4mh8nxa7h69.jpeg?q=70",
    img2:"https://rukminim1.flixcart.com/image/416/416/keg02a80/fmcg-combo/w/v/e/classic-dry-fruits-almonds-cashews-raisins-and-cranberries-original-imafv42cfgqhht3y.jpeg?q=70",
    img3:"https://rukminim1.flixcart.com/image/416/416/keekmfk0/nut-dry-fruit/r/m/z/1-california-broken-akhrot-tukda-pouch-eighty7-original-imafv3hcj7yhexmp.jpeg?q=70",
    img4:"https://rukminim1.flixcart.com/image/416/416/keekmfk0/fmcg-combo/w/v/e/classic-dry-fruits-almonds-cashews-raisins-and-cranberries-original-imafv3n4vtrfze42.jpeg?q=70",
    alt: "Product Image 1",
    product: "Dry Fruits",
    price: "₹441",
    // desc: "Fortiune oil",
    category:"grocery",
    prod_info:"Eighty7 Classic Dry Fruits Combo  (California Almonds-100g, Cashews-100g, Raisins-100g, Dried Cranberries-100g)",
  },
  {
    id:11,
    src: "https://rukminim1.flixcart.com/image/416/416/l0lbrm80/shopsy-festive-gift-box/w/n/d/7-nestle-and-dairy-milk-gift-comboholi-chocolate-gift-holi-gift-original-imagcchazngmjyzs.jpeg?q=70",
    img1:"https://rukminim1.flixcart.com/image/416/416/l0lbrm80/shopsy-festive-gift-box/r/o/q/7-11-pieces-chocolate-trayholi-chocolate-gift-holi-gift-original-imagccgdgebuzukj.jpeg?q=70",
    img2:"https://rukminim1.flixcart.com/image/416/416/l0lbrm80/shopsy-festive-gift-box/r/o/q/7-11-pieces-chocolate-trayholi-chocolate-gift-holi-gift-original-imagccgdgebuzukj.jpeg?q=70",
    img3:"https://rukminim1.flixcart.com/image/416/416/kl2mljk0/chocolate/c/x/v/191-chocolates-combo-for-valentine-tray-loaded-with-chocolate-1-original-imagyabx4yruhfgn.jpeg?q=70",
    img4:"https://rukminim1.flixcart.com/image/416/416/kmxsakw0/fmcg-combo/u/x/t/three-layered-chocolatey-love-bouquet-chocolate-gifts-gifts-of-original-imagfqfmrbgymd8r.jpeg?q=70",
    alt: "Product Image 2",
    product: "Chocolate",
    price: "₹289",
    // desc: "Moong Dal",
    category:"grocery",
    prod_info:"SurpriseForU Chocolate Gift | 11 Pieces Chocolate Tray Combo  (1 Tray - 1 Perk - 1 Kitkat - 3 Dairy Milk - 1 5Star - 5 Choclairs)"
  },
  {
    id:12,
    src: "https://rukminim1.flixcart.com/image/416/416/k9x3v680/fmcg-combo/h/9/n/moongbadi-disco-papad-besan-gatta-hand-made-papad-marwadi-sukha-original-imafrm2z5mdhzd6q.jpeg?q=70",
    img1:"https://rukminim1.flixcart.com/image/416/416/k5fn3ww0/fryum-papad/u/b/d/4000-papad-party-pack-bikaneri-disco-papd-400g-pack-of-10-fryums-original-imafz3twhmzrhjw6.jpeg?q=70",
    img2:"https://rukminim1.flixcart.com/image/416/416/k9he0sw0/snack-savourie/9/j/4/1000-moong-badi-vadi-hingwadi-wadian-rajasthani-famous-hand-made-original-imafr9qvcpxmyh5u.jpeg?q=70",
    img3:"https://rukminim1.flixcart.com/image/416/416/k69ncsw0/snack-savourie/s/u/m/400-traditional-rajasthani-sundried-homemade-dry-besan-gatta-original-imafzqpygfntfxzz.jpeg?q=70",
    img4:"https://rukminim1.flixcart.com/image/416/416/k5fn3ww0/fryum-papad/d/z/h/4000-papad-party-pack-bikaneri-hand-made-papd-400g-pack-of-10-original-imafz3twhca6xkyh.jpeg?q=70",
    alt: "Product Image 3",
    product: "Disco Papad",
    price: "₹310",
    // desc: "Ashirvad Atta",
    category:"grocery",
    prod_info:"Yuvraj Food Product moongBadi | Disco Papad | Besan Gatta | Hand made Papad ( Marwadi sukha saag ) Combo  (Badi 200 Gm, Disco Papad 200 Gm, Besan Gatta 200 Gm , Papad 200 gm)"
  },
  {
    id:13,
    src: "https://rukminim1.flixcart.com/image/416/416/kzygpzk0/fmcg-combo/c/4/u/premium-quality-arhar-and-chana-dal-combo-750-g-each-6-goshudh-original-imagbuvy2dsceahg.jpeg?q=70",
    img1:"https://rukminim1.flixcart.com/image/416/416/kzygpzk0/fmcg-combo/p/y/w/premium-quality-arhar-and-chana-dal-combo-750-g-each-6-goshudh-original-imagbuvy5ykxedwm.jpeg?q=70",
    img2:"https://rukminim1.flixcart.com/image/416/416/k98tdow0/fmcg-combo/v/j/s/premium-quality-masoor-dal-and-moong-mogar-combo-750g-each-original-imafr2w8czmugezh.jpeg?q=70",
    img3:"https://rukminim1.flixcart.com/image/416/416/k98tdow0/fmcg-combo/v/j/s/premium-quality-masoor-dal-and-moong-mogar-combo-750g-each-original-imafr2w8c8zmcyrc.jpeg?q=70",
    img4:"https://rukminim1.flixcart.com/image/416/416/k91o6fk0/fmcg-combo/y/y/h/premium-quality-green-moong-dal-and-moong-mogar-dal-combo-original-imafqx6gr7dasagt.jpeg?q=70",
    alt: "Product Image 4",
    product: " Dal Combo",
    price: "₹445",
    // desc: "Maggie Noodels",
    category:"grocery",
    prod_info:"Goshudh Premium Quality Arhar And Chana Dal Combo (750 g each) Combo  (Arhar Dal 750 gm, Chana Dal 750 gm)"
  },
  {
    id:14,
    src: "https://rukminim1.flixcart.com/image/416/416/l1nwnm80/fmcg-combo/j/w/d/easter-1-large-eggs-gift-box-pack-online-chocolate-eggs-bunnies-original-imagd6dh6tngy3w8.jpeg?q=70",
    img1:"https://rukminim1.flixcart.com/image/416/416/l0lbrm80/fmcg-combo/t/o/v/easter-1-large-eggs-gift-box-pack-online-chocolate-eggs-bunnies-original-imagcckvmsvqtysc.jpeg?q=70",
    img2:"https://rukminim1.flixcart.com/image/416/416/l0lbrm80/fmcg-combo/w/g/l/easter-1-large-eggs-gift-box-pack-online-chocolate-eggs-bunnies-original-imagcckvhv8hxtyz.jpeg?q=70",
    img3:"https://rukminim1.flixcart.com/image/416/416/l0wrafk0/chocolate/m/e/e/150-easter-9-chocolate-egg-tin-1-zoroy-luxury-chocolate-original-imagch3zuttu8gv4.jpeg?q=70",
    img4:"https://rukminim1.flixcart.com/image/416/416/xif0q/chocolate/m/n/w/180-easter-3-colourful-eggs-chocolate-gift-sets-for-corporate-original-imagnhwznpstbzgz.jpeg?q=70",
    alt: "Product Image 5",
    product: "Chocolate eggs",
    price: "₹424",
    // desc: "Unibic Cookies",
    category:"grocery",
  },
  {
    id:15,
    src: "https://rukminim1.flixcart.com/image/416/416/xif0q/milk-drink-mix/b/f/3/-original-imagnjznf3emnx3g.jpeg?q=70",
    img1:"https://rukminim1.flixcart.com/image/416/416/xif0q/milk-drink-mix/j/j/z/-original-imagnjnype9ssxg3.jpeg?q=70",
    img2:"https://rukminim1.flixcart.com/image/416/416/xif0q/milk-drink-mix/j/j/z/-original-imagnjnype9ssxg3.jpeg?q=70",
    img3:"https://rukminim1.flixcart.com/image/416/416/xif0q/milk-drink-mix/u/p/3/-original-imagnjzn5fpnvnne.jpeg?q=70",
    img4:"https://rukminim1.flixcart.com/image/416/416/xif0q/milk-drink-mix/u/q/h/-original-imagnjny4qzqhpgc.jpeg?q=70",
    alt: "Product Image 6",
    product: "BournVita",
    price: "₹214",
    // desc: "Health Drink",
    category:"grocery",
    prod_info:"Cadbury Bournvita 5 Star Magic Health Drink Pouch  (500 g)",
  },
  {
    id:16,
    src: "https://rukminim1.flixcart.com/image/416/416/js4yljk0/fruit/s/u/r/3-un-branded-whole-original-imafdsfxhnqhgn3d.jpeg?q=70",
    img1:"https://rukminim1.flixcart.com/image/416/416/ksru0sw0/fruit/r/w/s/200-1-unbranded-whole-original-imag69ffb9y2hqxt.jpeg?q=70",
    img2:"https://rukminim1.flixcart.com/image/416/416/ked56kw0/fruit/q/c/v/3-un-branded-whole-original-imafv2ftyhehg4zn.jpeg?q=70",
    img3:"https://rukminim1.flixcart.com/image/416/416/ksru0sw0/fruit/r/w/s/200-1-unbranded-whole-original-imag69ffb9y2hqxt.jpeg?q=70",
    img4:"https://rukminim1.flixcart.com/image/416/416/ktaeqvk0/fruit/u/6/m/1-1-un-branded-whole-original-imag6z5cn7hw7zdy.jpeg?q=70",
    alt: "Product Image 7",
    product: "Fruits",
    price: "₹96",
    // desc: "Grapes",
    category:"grocery",
    prod_info:"Kiwi Golden Imported 1 Units"
  },
  {
    id:17,
    src: "https://rukminim1.flixcart.com/image/416/416/jvv9zm80/honey/e/c/8/750-raw-honey-dadev-original-imafgzgmkf5u2vug.jpeg?q=70",
    img1:"https://rukminim1.flixcart.com/image/416/416/jvv9zm80/honey/e/c/8/750-raw-honey-dadev-original-imafgzgmnbkarvfj.jpeg?q=70",
    img2:"https://rukminim1.flixcart.com/image/416/416/jwxuvm80/honey/e/c/8/750-organic-and-raw-honey-dadev-original-imafhe4drxmfhmur.jpeg?q=70",
    img3:"https://rukminim1.flixcart.com/image/416/416/jxxkvww0/honey/w/h/a/175-organic-and-raw-honey-dadev-original-imafccvmmuadz8by.jpeg?q=70",
    img4:"https://rukminim1.flixcart.com/image/416/416/jxxkvww0/honey/w/h/a/175-organic-and-raw-honey-dadev-original-imafg9kch2jdew82.jpeg?q=70",
    alt: "Product Image 8",
    product: "Honey",
    price: "₹600",
    // desc: "Dabur honey",
    category:"grocery",
    prod_info:"DADEV NMR Tested 100% Pure Forest Raw Organic Honey PLASTIC JAR  (750 g)"
  },
  {
    id:18,
    src: "https://rukminim1.flixcart.com/image/416/416/l37mtu80/toothpaste/b/d/o/-original-imagednexfmjazd4.jpeg?q=70",
    img1:"https://rukminim1.flixcart.com/image/416/416/xif0q/toothpaste/u/e/v/-original-imagk8xfedvmzwj5.jpeg?q=70",
    img2:"https://rukminim1.flixcart.com/image/416/416/xif0q/toothpaste/h/w/d/-original-imagk8xfgkygyff5.jpeg?q=70",
    img3:"https://rukminim1.flixcart.com/image/416/416/xif0q/toothpaste/s/4/6/50-visible-white-o2-teeth-whitening-toothpaste-aromatic-mint-50g-original-imaghwnyxarhxmjh.jpeg?q=70",
    img4:"https://rukminim1.flixcart.com/image/416/416/xif0q/toothpaste/x/r/p/50-visible-white-o2-teeth-whitening-toothpaste-aromatic-mint-50g-original-imaghwnyubfs5mbj.jpeg?q=70",
    alt: "Product Image 9",
    product: "Toothpaste",
    price: "₹349",
    // desc: "Colgate Maxfresh",
    category:"grocery",
    prod_info:"Colgate Visible White O2, Teeth Whitening Toothpaste, Aromatic Mint, 50g, Active Oxygen Toothpaste  (50 g)"
  },
  {
    id:19,
    src: "https://rukminim1.flixcart.com/image/416/416/kjkbv680-0/shoe-rack/c/q/v/00p-dewberries-blue-original-imafz3nvq8gzpg5c.jpeg?q=70",
    img1:"https://rukminim1.flixcart.com/image/416/416/kjkbv680-0/shoe-rack/c/q/v/00p-dewberries-blue-original-imafz3nvq8gzpg5c.jpeg?q=70",
    img2:"https://rukminim1.flixcart.com/image/416/416/kigbjbk0-0/shoe-rack/i/u/i/shoe-organizer-s-v-enterprises-original-imafy8h2jtb7n66b.jpeg?q=70",
    img3:"https://rukminim1.flixcart.com/image/416/416/kpbipow0/shoe-rack/t/i/a/chappal-stand-shoe-stand-collapsible-shoe-rack-cover-foldable-original-imag3kw3ebcgwqvz.jpeg?q=70",
    img4:"https://rukminim1.flixcart.com/image/416/416/kjkbv680-0/shoe-rack/k/3/p/00p-dewberries-brown-original-imafz3nzntsnueuf.jpeg?q=70",
    alt: "Product Image 1",
    product: "Shoe Rack",
    price: "₹3000",
    // desc: "KSP metal shoe rack",
    category:"home",
    prod_info:"ROBMOB Metal Shoe Stand  (Black, 12 Shelves, DIY(Do-It-Yourself))",
  },
  {
    id:20,
    src: "https://rukminim1.flixcart.com/image/416/416/kyyqpow0/mat/k/w/u/medium-jalebi06-5pc-5-jalebi06-5pc-shf-original-imagb2n9efwqydh9.jpeg?q=70",
    img1:"https://rukminim1.flixcart.com/image/416/416/xif0q/mat/2/e/7/large-00160-5-shf00160-shf-original-imaggts6wxjyzrd2.jpeg?q=70",
    img2:"https://rukminim1.flixcart.com/image/416/416/xif0q/mat/n/a/a/large-00160-5-shf00160-shf-original-imaggts6hcgjphux.jpeg?q=70",
    img3:"https://rukminim1.flixcart.com/image/416/416/xif0q/mat/l/b/m/large-00160-5-shf00160-shf-original-imaggts6hgtyknkv.jpeg?q=70",
    img4:"https://rukminim1.flixcart.com/image/416/416/kfk0e4w0/mat/h/f/z/medium-doormat-01-doormat-01-expart-original-imafvzvynyt25std.jpeg?q=70",
    alt: "Product Image 2",
    product: "Mat",
    price: "₹229",
    // desc: "Door mat",
    category:"home",
    prod_info:"Fresh Zone Polyester Door Mat  (Multicolor, Medium, Pack of 5)"
  },
  {
    id:21,
    src: "https://rukminim1.flixcart.com/image/416/416/xif0q/chopper/p/q/a/stainless-steel-blade-powerful-mini-handy-quick-chopper-450-ml-original-imagz763twndzatf.jpeg?q=70",
    img1:"https://rukminim1.flixcart.com/image/416/416/xif0q/shopsy-chopper/9/f/x/no-dori-chopper-450ml-chopper-redsky-original-imagh29wvd9vzyuk.jpeg?q=70",
    img2:"https://rukminim1.flixcart.com/image/416/416/kthjy4w0/chopper/n/l/m/fksbjd650blu-flipkart-smartbuy-original-imag6tn6j67zgq9w.jpeg?q=70",
    img3:"https://rukminim1.flixcart.com/image/416/416/l3bx5e80/chopper/i/p/i/-original-imageh5wta2jqruz.jpeg?q=70",
    img4:"https://rukminim1.flixcart.com/image/416/416/k3vwxow0/chopper/q/3/h/quick-sharp-mini-chopper-zabolo-original-imafmxatsvzhfgxr.jpeg?q=70",
    alt: "Product Image 3",
    product: "Chopper",
    price: "₹199",
    // desc: "Vegetable chopper",
    category:"home",
    prod_info:"Flipkart SmartBuy 500ml Sharp Chopper  (1 chopper)",
  },
  {
    id:22,
    src: "https://rukminim1.flixcart.com/image/416/416/l34ry4w0/home-temple/c/j/u/23-46-5-jl-nacural-rajasthani-art-56-original-imagebt5h6hgdzxw.jpeg?q=70",
    img1:"https://rukminim1.flixcart.com/image/416/416/l34ry4w0/home-temple/c/i/8/23-46-5-jl-nacural-rajasthani-art-56-original-imagebt5xy6wnwpk.jpeg?q=70",
    img2:"https://rukminim1.flixcart.com/image/416/416/kf8kvbk0/home-temple/c/z/z/ka-ht-50-craftsfort-original-imafvrf7krcwptzv.jpeg?q=70",
    img3:"https://rukminim1.flixcart.com/image/416/416/kalecnk0/home-temple/j/e/f/puja-mandir-702-marusthalee-original-imafs4r3pvyf5ygs.jpeg?q=70",
    img4:"https://rukminim1.flixcart.com/image/416/416/kalecnk0/home-temple/j/e/f/puja-mandir-702-marusthalee-original-imafs4r3bne2c5fz.jpeg?q=70",
    alt: "Product Image 4",
    product: "Home Temple",
    price: "₹2,479",
    // desc: "Wooden puja stand",
    category:"home",
    prod_info:"Marusthalee Mandir Puja Ghar Solid Wood Home Temple  (Height: 60, Knock Down)",
  },
  {
    id:23,
    src: "https://rukminim1.flixcart.com/image/416/416/xif0q/lunch-box/h/v/3/1400-executive3containerslunchbox-microwavesafesteel-3-original-imagzbgfpvufbvas.jpeg?q=70",
    img1:"https://rukminim1.flixcart.com/image/416/416/kvba7bk0/lunch-box/t/g/e/1600-sparkle-z-2-blue-mastercook-4-original-imag88uyywwqas4c.jpeg?q=70",
    img2:"https://rukminim1.flixcart.com/image/416/416/kvba7bk0/lunch-box/w/3/r/1600-sparkle-z-2-pink-mastercook-4-original-imag88vyhhfnnhwq.jpeg?q=70",
    img3:"https://rukminim1.flixcart.com/image/416/416/kvba7bk0/lunch-box/1/j/5/1600-sparkle-z-2-yellow-mastercook-4-original-imag88uxzz67kmdj.jpeg?q=70",
    img4:"https://rukminim1.flixcart.com/image/416/416/ktg4ia80/lunch-box/y/f/g/1-lunch-box-with-bag-sunhet-enterprise-3-original-imag6saxku7hntdv.jpeg?q=70",
    alt: "Product Image 5",
    product: "Lunch box",
    price: "₹389",
    // desc: "HP Laptop",
    category:"home",
    prod_info:"MASTER COOK SPARKLE Z 2 YELLOW 4 Containers Lunch Box  (1600 ml)",
  },
  {
    id:24,
    src: "https://rukminim1.flixcart.com/image/416/416/xif0q/kid-seating/s/n/2/-original-imag2xffjhwckav2.jpeg?q=70",
    img1:"https://rukminim1.flixcart.com/image/416/416/kshtxu80/kid-seating/c/2/7/15-black-cotton-35-2-516311336-red-rcnd-45-red-original-imag625xqcjgbhsu.jpeg?q=70",
    img2:"https://rukminim1.flixcart.com/image/416/416/ktd9mkw0/kid-seating/h/7/o/36-red-25-cotton-1-2-rbs-01-red-sarika-enterprises-black-30-original-imag6qc5fvzygmab.jpeg?q=70",
    img3:"https://rukminim1.flixcart.com/image/416/416/kqco5u80/inflatable-product/n/f/s/baby-sofa-seat-soft-plush-cushion-cotton-safety-car-chair-with-original-imag4dk2ajjcfz36.jpeg?q=70",
    img4:"https://rukminim1.flixcart.com/image/416/416/kr9jafk0/stuffed-toy/j/n/o/mickey-shape-soft-plush-cushion-baby-sofa-seat-or-rocking-chair-original-imag533s6gwfbzzz.jpeg?q=70",
    alt: "Product Image 6",
    product: " Fabric Sofa",
    price: "₹440",
    // desc: "Exhaust fan for kitchen",
    category:"home",
    prod_info:"Sarika Enterprises Mickey Mouse Shaped Soft Plush Cushion Fabric Sofa  (Finish Color - Black, Pre-assembled)",
  },
  {
    id:25,
    src: "https://rukminim1.flixcart.com/image/416/416/xif0q/bedsheet/e/q/l/elastic-comfort-collection-light-yellow-print-glaze-cotton-250-original-imagjkbgmtavaxts.jpeg?q=70",
    img1:"https://rukminim1.flixcart.com/image/416/416/xif0q/bedsheet/i/l/s/printed-cg-bst-db654-flat-cg-homes-original-imaghqavgauxsm5b.jpeg?q=70",
    img2:"https://rukminim1.flixcart.com/image/416/416/xif0q/bedsheet/w/v/l/traditional-jaipuri-print-1-round-gulab-green-flat-cosito-original-imagh8d8gg7dhj4g.jpeg?q=70",
    img3:"https://rukminim1.flixcart.com/image/416/416/xif0q/bedsheet/z/v/2/traditional-jaipuri-print-1-round-gulab-pink-flat-cosito-original-imagh8ddpgg5mrmh.jpeg?q=70",
    img4:"https://rukminim1.flixcart.com/image/416/416/l3hmwsw0/bedsheet/h/o/r/triangle-pink-new-with-two-pillow-covers-1-trianglepinknew1-flat-original-imagekwhcrwfnv8w.jpeg?q=70",
    alt: "Product Image 7",
    product: "Bedsheet",
    price: "₹239",
    // desc: "BSB Cotton Bedsheet",
    category:"home",
    prod_info:"RisingStar 220 TC Cotton Double Geometric Flat Bedsheet  (Pack of 1, Multicolor)",
  },
  {
    id:26,
    src: "https://rukminim1.flixcart.com/image/416/416/jz7az680/air-freshener/m/g/z/270-rose-garden-room-spray-liquid-odonil-original-imafj9qbzjnhb5cu.jpeg?q=70",
    img1:"https://rukminim1.flixcart.com/image/416/416/kit6hzk0/air-freshener/s/a/5/137-room-spray-sandal-bouquet-liquid-odonil-original-imafygwh3x2w6zzh.jpeg?q=70",
    img2:"https://rukminim1.flixcart.com/image/416/416/xif0q/air-freshener/t/c/b/-original-imaghy6ffwrfuh95.jpeg?q=70",
    img3:"https://rukminim1.flixcart.com/image/416/416/kit6hzk0/air-freshener/m/8/e/240-room-spray-liquid-odonil-original-imafygwhstfagxyg.jpeg?q=70",
    img4:"https://rukminim1.flixcart.com/image/416/416/kpft18w0/air-freshener/t/m/h/room-spray-liquid-odonil-original-imag3zghguw3srau.jpeg?q=70",
    alt: "Product Image 8",
    product: "Freshener",
    price: "₹128",
    // desc: "Godrej aer freshener",
    category:"home",
    prod_info:"Odonil Room Freshening Lavender Mist Spray  (220 ml)"
  },
  {
    id:27,
    src: "https://rukminim1.flixcart.com/image/416/416/xif0q/rocking-chair/t/4/y/60-1-seater-rosewood-sheesham-128-18-rockingh836-brown-soul-original-imagz74hvvb2xrxg.jpeg?q=70",
    img1:"https://rukminim1.flixcart.com/image/416/416/xif0q/rocking-chair/j/i/s/60-1-seater-rosewood-sheesham-128-18-rockingh469-grey-soul-light-original-imagz63fyupbq66e.jpeg?q=70",
    img2:"https://rukminim1.flixcart.com/image/416/416/l1b1oy80/rocking-chair/l/e/0/1092-1-seater-610-rosewood-sheesham-20-fh-rc-25-brown-original-imagcwh9pfjgzgfh.jpeg?q=70",
    img3:"https://rukminim1.flixcart.com/image/416/416/xif0q/rocking-chair/r/q/r/15-1-seater-rosewood-sheesham-110-18-dret0691-grey-india-wood-original-imagkyzekm4mvtgr.jpeg?q=70",
    img4:"https://rukminim1.flixcart.com/image/416/416/xif0q/rocking-chair/4/j/n/60-1-seater-rosewood-sheesham-128-18-rockingh9689-black-soul-original-imagz6z8t9n46afd.jpeg?q=70",
    alt: "Product Image 9",
    product: "Rolling Chair",
    price: "₹15,999",
    // desc: "Seater home sofa",
    category:"home",
    prod_info:"India wood mart Sheesham Wood Rocking Chair,Wooden Rolling Chair, Wooden Easy Chair Engineered Wood 1 Seater Rocking Chairs  (Finish Color - Brown, Pre-assembled)"
  },
  {
    id:28,
    src: "https://m.media-amazon.com/images/I/81uL5oJmQxL._AC_UY218_.jpg",
    img1:"https://rukminim1.flixcart.com/image/416/416/l33cia80/regionalbooks/d/p/r/the-english-vocab-wits-read-lead-succeed-by-gopal-verma-original-imageafhzem3wnrk.jpeg?q=70",
    img2:"https://rukminim1.flixcart.com/image/416/416/kl8ccy80/regionalbooks/f/k/4/blossom-english-vocabulary-books-for-5-to-10-year-old-kids-vocab-original-imagyefweypznbrd.jpeg?q=70",
    img3:"https://rukminim1.flixcart.com/image/416/416/xif0q/regionalbooks/s/t/z/neetu-singh-vocab-15000-vocabularies-original-imagmsf7pvr5tnzp.jpeg?q=70",
    img4:"https://rukminim1.flixcart.com/image/416/416/xif0q/regionalbooks/c/8/7/rankers-vocab-sanjeevani-original-imaghsh3kengydvp.jpeg?q=70",
    alt: "Product Image 1",
    product: "Vocabulary",
    price: "₹359",
    // desc: "English vocabulary",
    category:"books",
    prod_info:"The English Vocab-Wits READ-LEAD-SUCCEED By Gopal Verma  (Paperback, GOPAL VERMA)",
  },
  {
    id:29,
    src: "https://rukminim1.flixcart.com/image/416/416/xif0q/book/x/d/z/the-blue-umbrella-original-imagmpj4ycrhc3xe.jpeg?q=70",
    img1:"https://rukminim1.flixcart.com/image/416/416/kufuikw0/book/5/s/y/diary-of-a-wimpy-kid-book-1-original-imag7jhrsrz6cgth.jpeg?q=70",
    img2:"https://rukminim1.flixcart.com/image/416/416/kqidx8w0/book/2/b/0/pandit-vishnu-sharma-s-panchatantra-for-children-original-imag4g64vux6ykjf.jpeg?q=70",
    img3:"https://rukminim1.flixcart.com/image/416/416/l4d2ljk0/book/m/8/e/-original-imagfa9rayz68vss.jpeg?q=70",
    img4:"https://rukminim1.flixcart.com/image/416/416/kqidx8w0/book/p/t/w/short-stories-from-panchatantra-original-imag4hpfg7zskqmc.jpeg?q=70",
    alt: "Product Image 2",
    product: "Mythology",
    price: "₹95",
    // desc: "Story books for kids",
    category:"books",
    prod_info:"Short Stories from Panchatantra - By Miss & Chief  (English, Paperback, unknown)",
  },
  {
    id:30,
    src: "https://rukminim1.flixcart.com/image/416/416/kjvrdzk0/book/r/z/h/forge-your-future-original-imafzcszxujbynnf.jpeg?q=70",
    img1:"https://rukminim1.flixcart.com/image/416/416/k7m8brk0/book/7/7/2/the-magic-of-believing-original-imafptemeuyygjuq.jpeg?q=70",
    img2:"https://rukminim1.flixcart.com/image/416/416/xif0q/book/d/i/f/chintan-karo-chinta-nahin-original-imagk252rtg58z3n.jpeg?q=70",
    img3:"https://rukminim1.flixcart.com/image/416/416/xif0q/book/a/o/f/ego-is-the-enemy-original-imagksr5jygfrs7c.jpeg?q=70",
    img4:"https://rukminim1.flixcart.com/image/416/416/jf8khow0/book/6/4/2/motivational-quotes-original-imaf3r3bgc9hkhnu.jpeg?q=70",
    alt: "Product Image 3",
    product: "Motivational ",
    price: "₹240",
    // desc: "Subconcious Mind",
    category:"books",
    prod_info:"Forge Your Future  (English, Paperback, Kalam A.P.J. Abdul)",
  },
  {
    id:31,
    src: "https://rukminim1.flixcart.com/image/416/416/kvsfhjk0/book/p/z/f/brain-activity-book-for-kids-200-activities-for-age-3-original-imag8hv3cftt6ydy.jpeg?q=70",
    img1:"https://rukminim1.flixcart.com/image/416/416/kvcpn680/book/0/0/y/brilliant-brain-activity-book-4-original-imag89ddcbtq9mkz.jpeg?q=70",
    img2:"https://rukminim1.flixcart.com/image/416/416/l1ch4sw0/regionalbooks/a/p/i/nurture-505-activities-book-for-kids-english-activity-workbook-original-imagcxmhgvvhhzpr.jpeg?q=70",
    img3:"https://rukminim1.flixcart.com/image/416/416/kvcpn680/book/p/r/r/brilliant-brain-activity-book-7-original-imag89ddgyegknrf.jpeg?q=70",
    img4:"https://rukminim1.flixcart.com/image/416/416/xif0q/book/c/j/4/brain-puzzles-for-kids-100-activities-original-imagh4z47vsf2zg2.jpeg?q=70",
    alt: "Product Image 4",
    product: "Kids",
    price: "₹112",
    // desc: "brain activity",
    category:"books",
    prod_info:"Brain Activity Book for Kids  (English, Paperback, unknown)",
  },
  {
    id:32,
    src: "https://rukminim1.flixcart.com/image/416/416/l2jcccw0/book/u/a/f/stock-market-investing-for-beginners-original-imagdune3gvxwtvm.jpeg?q=70",
    img1:"https://rukminim1.flixcart.com/image/416/416/jkmwdjk0/regionalbooks/a/z/e/31-stock-market-trading-tips-original-imaf7rhmhdc5xwcx.jpeg?q=70",
    img2:"https://rukminim1.flixcart.com/image/416/416/l3lx8cw0/book/d/a/o/basics-of-stock-market-complete-guide-for-stock-beginners-arvind-original-imagezrgsfdykzv5.jpeg?q=70",
    img3:"https://rukminim1.flixcart.com/image/416/416/jkmwdjk0/regionalbooks/z/h/2/guide-to-indian-stock-market-original-imaf6hyxhhyryggp.jpeg?q=70",
    img4:"https://rukminim1.flixcart.com/image/416/416/kupuljk0/book/0/k/p/stock-market-mein-nivesh-aur-trading-ke-secrets-original-imag7rqngwd8wumm.jpeg?q=70",
    alt: "Product Image 5",
    product: "Stock Market",
    price: "₹764",
    // desc: "Price action trading",
    category:"books",
    prod_info:"Stock Market Investing for Beginners  (English, Paperback, Tycho Press)",
  },
  {
    id:33,
    src: "https://rukminim1.flixcart.com/image/416/416/kwmfqfk0/book/m/u/v/selected-poems-original-imag99nnpamacmhz.jpeg?q=70",
    img1:"https://rukminim1.flixcart.com/image/416/416/kqidx8w0/book/m/l/9/100-selected-poems-william-wordsworth-original-imag4g42gdzftuhn.jpeg?q=70",
    img2:"https://rukminim1.flixcart.com/image/416/416/book/2/4/8/tishnagi-hindi-poems-original-imaef36thdfmtsz2.jpeg?q=70",
    img3:"https://rukminim1.flixcart.com/image/416/416/kufuikw0/book/5/s/k/selected-poems-tennyson-original-imag7jjhfpdvmqrh.jpeg?q=70",
    img4:"https://rukminim1.flixcart.com/image/416/416/kt39jm80/book/x/k/u/100-selected-poems-original-imag6hsh5asvwkup.jpeg?q=70",
    alt: "Product Image 6",
    product: "Poems",
    price: "₹160",
    // desc: "50 greatest poems",
    category:"books",
    prod_info:"Selected Poems  (English, Paperback, unknown)",
  },
  {
    id:34,
    src: "https://rukminim1.flixcart.com/image/416/416/kjabs7k0-0/book/w/b/u/ghost-stories-of-shimla-hills-original-imafyvxzhzvnvgbz.jpeg?q=70",
    img1:"https://rukminim1.flixcart.com/image/416/416/ki7qw7k0-0/book/f/l/v/50-greatest-horror-stories-original-imafy246jjma5h9y.jpeg?q=70",
    img2:"https://rukminim1.flixcart.com/image/416/416/kura1e80/book/t/r/o/horror-stories-original-imag7tf5kzygb2wy.jpeg?q=70",
    img3:"https://rukminim1.flixcart.com/image/416/416/book/5/0/2/horror-stories-original-imadfzjp345hh4eq.jpeg?q=70",
    img4:"https://rukminim1.flixcart.com/image/416/416/j8ndea80/book/7/2/6/revenge-of-the-evil-tantric-horror-stories-from-india-original-imaeymzfhgeunzge.jpeg?q=70",
    alt: "Product Image 7",
    product: "Horror",
    price: "₹166",
    // desc: "Horror Stories",
    category:"books",
    prod_info:"Ghost Stories of Shimla Hills  (English, Paperback, Chaudhry Minakshi)",
    
  },
  {
    id:35,
    src: "https://rukminim1.flixcart.com/image/416/416/l1jmc280/magazine/t/t/k/32-2022-09-21-70445480-ikea-original-imagd2z8khdjqtcr.jpeg?q=70",
    img1:"https://rukminim1.flixcart.com/image/416/416/xif0q/magazine/d/p/v/72-2022-12-05-72819-organic-sunrise-natural-original-imagmdk6pug8vsgd.jpeg?q=70",
    img2:"https://rukminim1.flixcart.com/image/416/416/xif0q/magazine/l/b/p/102-2022-11-01-49029020-indiatoday-original-imagjvffv3hmpuzb.jpeg?q=70",
    img3:"https://rukminim1.flixcart.com/image/416/416/xif0q/magazine/z/a/g/100-2022-10-31-123456789-fabulous-original-imagj4pga2he37ve.jpeg?q=70",
    img4:"https://rukminim1.flixcart.com/image/416/416/l3hmwsw0/magazine/p/o/4/75-2022-06-01-123456787-blitzz-today-original-imagehhhxa5uhucf.jpeg?q=70",
    alt: "Product Image 8",
    product: "Magazines",
    price: "₹474",
    // desc: "Belly to Baby",
    category:"books",
    prod_info:"IKEA Magazines  (English)",
  },
  {
    id:36,
    src: "https://rukminim1.flixcart.com/image/416/416/k5vcya80/book/1/2/3/why-i-am-an-atheist-original-imafzgz6mn7n6wmz.jpeg?q=70",
    img1:"https://rukminim1.flixcart.com/image/416/416/juk4gi80/book/4/6/6/wings-of-fire-original-imaffmk4gx5pxqvf.jpeg?q=70",
    img2:"https://rukminim1.flixcart.com/image/416/416/kiew3gw0-0/book/o/j/n/elon-musk-original-imafy7tnhhydukwc.jpeg?q=70",
    img3:"https://rukminim1.flixcart.com/image/416/416/l2jcccw0/book/e/e/a/my-journey-original-imagduuehhjd3hgt.jpeg?q=70",
    img4:"https://rukminim1.flixcart.com/image/416/416/xif0q/book/s/t/l/motivating-thoughts-of-swami-vivekananda-original-imaggnmk9edg2g9b.jpeg?q=70",
    alt: "Product Image 9",
    product: "Biography",
    price: "₹175",
    // desc: "Steve Jobs",
    category:"books",
    prod_info:"Why I Am an Atheist  (English, Undefined, Singh Bhagat)",
  },

  {
    id:37,
    src: "https://rukminim1.flixcart.com/image/832/832/xif0q/shopsy-top/n/8/l/s-shopsytee-empire-black-dream-beauty-fashion-original-imagjzbtvyc3vsah.jpeg?q=70",
    img1:"https://rukminim1.flixcart.com/image/832/832/xif0q/top/d/6/i/s-4261-sheetal-associates-original-imagjtft5jrzgwph.jpeg?q=70",
    img2:"https://rukminim1.flixcart.com/image/832/832/xif0q/top/s/n/l/xxl-0013-top-dl-fashion-original-imaggf53g4fwqhye.jpeg?q=70",
    img3:"https://rukminim1.flixcart.com/image/832/832/xif0q/top/j/e/v/m-top-netleaf-original-imagh7ypxb4vznrt.jpeg?q=70",
    img4:"https://rukminim1.flixcart.com/image/832/832/xif0q/top/2/d/j/m-top-22-shree-i-saheb-original-imaggjv58kpskjak.jpeg?q=70",
    alt: "Product Image 1",
    product: "Women Top",
    price: "₹399",
    // desc: "Casual top",
    category:"fashion",
    prod_info:"Casual Flared Sleeves Solid Women Maroon Top",
  },
  {
    id:38,
    src: "https://rukminim1.flixcart.com/image/832/832/l51d30w0/shoe/z/w/c/10-mrj1914-10-aadi-white-black-red-original-imagft9k9hydnfjp.jpeg?q=70",
    img1:"https://rukminim1.flixcart.com/image/832/832/xif0q/shoe/c/d/i/7-95000215-41-roamra-white-original-imag4ahytjmqdzz8-bb.jpeg?q=70",
    img2:"https://rukminim1.flixcart.com/image/832/832/xif0q/shoe/d/n/l/9-fast-white-perrot-sfr-white-perrot-original-imagj52ctxvu6ewf.jpeg?q=70",
    img3:"https://rukminim1.flixcart.com/image/832/832/xif0q/shoe/p/y/0/-original-imagg5rfsacakzqz.jpeg?q=70",
    img4:"https://rukminim1.flixcart.com/image/832/832/kumzpu80/shoe/w/q/1/10-rpd128-10-rapidbox-white-original-imag7pvffzpzpxzk.jpeg?q=70",
    alt: "Product Image 2",
    product: "Footwear",
    price: "₹571",
    // desc: "Summer sandal",
    category:"fashion",
    prod_info:"Stylish & Trendy Sneakers For Men  (White)"
  },
  {
    id:39,
    src: "https://rukminim1.flixcart.com/image/832/832/xif0q/backpack/0/u/w/-original-imagmek8e5f5zx6g.jpeg?q=70",
    img1:"https://rukminim1.flixcart.com/image/832/832/xif0q/backpack/5/u/0/-original-imagmek8fksfrzxq.jpeg?q=70",
    img2:"https://rukminim1.flixcart.com/image/832/832/xif0q/backpack/m/o/5/-original-imagg6rrm4hcqtdr.jpeg?q=70",
    img3:"https://rukminim1.flixcart.com/image/832/832/xif0q/backpack/m/j/h/-original-imagg6rrcehythuq.jpeg?q=70",
    img4:"https://rukminim1.flixcart.com/image/832/832/xif0q/backpack/k/7/8/-original-imagmvqavdbqeykc.jpeg?q=70",
    alt: "Product Image 3",
    product: "Bags",
    price: "₹729",
    // desc: "Shoulder bags",
    category:"fashion",
    prod_info:"Large 34 L Backpack One Spacious Unisex Multpurpose bag with Laptop Sleeve CORE V2  (Yellow)",
  },
  {
    id:40,
    src: "https://rukminim1.flixcart.com/image/832/832/xif0q/ethnic-set/5/k/m/s-emp8027blue-emperus-original-imagyzrm6zbtqfbt-bb.jpeg?q=70",
    img1:"https://rukminim1.flixcart.com/image/832/832/xif0q/kurta/a/c/g/m-ae-kurta-117-ananta-enterprise-original-imagh8cxjvdhycvu.jpeg?q=70",
    img2:"https://rukminim1.flixcart.com/image/832/832/xif0q/ethnic-set/5/n/1/4xl-slk-111-blue-subh-laxmi-original-imag8tfw8wpmt6r2.jpeg?q=70", 
    img3:"https://rukminim1.flixcart.com/image/832/832/xif0q/salwar-kurta-dupatta/l/e/x/s-kurta-set-dev-fashion-original-imaghyd4cwxfzjzb.jpeg?q=70",
    img4:"https://rukminim1.flixcart.com/image/832/832/xif0q/salwar-kurta-dupatta/r/z/b/s-bt-105-primhi-original-imaghzq4zjnkbfkq.jpeg?q=70",
    alt: "Product Image 4",
    product: "Women Kurta and Skirt Set",
    price: "₹545",
    // desc: "Floral top with Pyjama",
    category:"fashion",
    prod_info:"Women Kurta and Skirt Set Viscose Rayon",
  },
  {
    id:41,
    src: "https://rukminim1.flixcart.com/image/832/832/kvzkosw0/jacket/o/b/c/s-no-14473534-here-now-original-imag8rfn7pjwrpbn.jpeg?q=70",
    img1:"https://rukminim1.flixcart.com/image/832/832/xif0q/jacket/c/u/f/m-mnt-7024-montrez-original-imag5hb9hqcc4qyy-bb.jpeg?q=70",
    img2:"https://rukminim1.flixcart.com/image/832/832/xif0q/sweatshirt/l/g/d/s-1jgswzipblack01-red-jugular-original-imag6bzc35nnzakf-bb.jpeg?q=70",
    img3:"https://rukminim1.flixcart.com/image/832/832/xif0q/track-top/t/j/u/m-hs8159-adidas-original-imagkxcdgahvd2zf.jpeg?q=70",
    img4:"https://rukminim1.flixcart.com/image/832/832/kwb07m80/jacket/y/q/p/-original-imag9yccnsh6fzey.jpeg?q=70",
    alt: "Product Image 5",
    product: "Jacket",
    price: "₹1,637",
    // desc: "Men's denim jacket",
    category:"fashion",
    prod_info:"Men Colorblock Sports Jacket",
  },
  {
    id:42,
    src: "https://rukminim1.flixcart.com/image/832/832/l4ln8nk0/sari/p/2/u/free-2535s934-samah-unstitched-original-imagfgq7pc2mc4vz.jpeg?q=70",
    img1:"https://rukminim1.flixcart.com/image/832/832/kzygpzk0/sari/b/3/p/free-2329s781-samah-unstitched-original-imagbugfqwbxpsj2.jpeg?q=70",
    img2:"https://rukminim1.flixcart.com/image/832/832/xif0q/sari/g/z/p/free-sps1139-1-soor-panchi-original-imaf9jawz8gcdjhy-bb.jpeg?q=70",
    img3:"https://rukminim1.flixcart.com/image/832/832/l0zm64w0/sari/x/l/p/free-mc-50-rani-kartvya-unstitched-original-imagcnksmzyktamm.jpeg?q=70",
    img4:"https://rukminim1.flixcart.com/image/832/832/kxaq7ww0/sari/o/k/q/free-grey-1692-6-kashvi-sarees-unstitched-original-imag9s7ggsjw2gcn.jpeg?q=70",
    alt: "Product Image 6",
    product: "Saree",
    price: "₹2870",
    // desc: "Silk embroider work",
    category:"fashion",
    prod_info:"Printed, Geometric Print, Embellished Bhagalpuri Silk Blend, Cotton Silk Saree  (Green, Pink)"
  },
  {
    id:43,
    src: "https://rukminim1.flixcart.com/image/832/832/xif0q/wallet-card-wallet/m/u/a/georgia-101ubf1010-wallet-urban-forest-original-imagmj53ezrvzvzj.jpeg?q=70",
    img1:"https://rukminim1.flixcart.com/image/832/832/xif0q/wallet-card-wallet/e/v/o/leo-1-4-5-ubf108brn1052-6-wallet-urban-forest-3-7-original-imagk8xebnhnezyg.jpeg?q=70",
    img2:"https://rukminim1.flixcart.com/image/832/832/ksqeky80/wallet-card-wallet/r/c/3/new-high-quality-genuine-men-s-leather-wallet-12-1-wh2055-5-original-imag68hpn7dpzvca.jpeg?q=70",
    img3:"https://rukminim1.flixcart.com/image/832/832/xif0q/wallet-card-wallet/e/v/o/leo-1-4-5-ubf108brn1052-6-wallet-urban-forest-3-7-original-imagk8xebnhnezyg.jpeg?q=70",
    img4:"https://rukminim1.flixcart.com/image/832/832/xif0q/wallet-card-wallet/o/p/s/oliver-ubf107cog1017-wallet-urban-forest-original-imaghefhjz9fszyj.jpeg?q=70",
    alt: "Product Image 7",
    product: "Wallet",
    price: "₹299",
    // desc: "Brown leather wallet",
    category:"fashion",
    prod_info:"Men Casual, Formal Blue Genuine Leather Wallet  (8 Card Slots)"
  },
  {
    id:44,
    src: "https://rukminim1.flixcart.com/image/832/832/kihqz680-0/jewellery-set/w/j/w/gold-plated-jewellery-long-traditional-maharani-coin-necklace-original-imafy9yud2f2ek7k.jpeg?q=70",
    img1:"https://rukminim1.flixcart.com/image/832/832/xif0q/jewellery-set/n/4/g/na-na-nc0106-litrik-original-imaghchew8gzgh44.jpeg?q=70",
    img2:"https://rukminim1.flixcart.com/image/832/832/xif0q/jewellery-set/h/s/5/na-na-te331-litrik-original-imaggk7pgzhpsx5h.jpeg?q=70",
    img3:"https://rukminim1.flixcart.com/image/832/832/l5h2xe80/jewellery-set/n/c/d/na-na-nc031-litrik-original-imagg4x85dmjxagz.jpeg?q=70",
    img4:"https://rukminim1.flixcart.com/image/832/832/xif0q/jewellery-set/3/j/b/na-d-ats-jewellery-set-brado-jewellery-original-imagj95nha9zscgb.jpeg?q=70",
    alt: "Product Image 8",
    product: "Jewellery",
    price: "₹422",
    // desc: "Solid silver chain",
    category:"fashion",
    prod_info:"Alloy Gold-plated Gold Jewel Set  (Pack of 1)",
  },
  {

    id:45,


    src: "https://m.media-amazon.com/images/I/71irYwattwL._AC_UL320_.jpg",

    src: "https://rukminim1.flixcart.com/image/832/832/xif0q/wallet-card-wallet/5/1/7/-original-imagnvuxfvcc2bze.jpeg?q=70",
    img1:"https://rukminim1.flixcart.com/image/832/832/xif0q/clutch/m/l/a/-original-imagnjumew4eh85v.jpeg?q=70",
    img2:"https://rukminim1.flixcart.com/image/832/832/xif0q/clutch/s/w/o/women-s-and-girls-handclutch-cum-mobile-handpurse-yafc-118-1801-original-imagk49zpeq4feyg.jpeg?q=70",
    img3:"https://rukminim1.flixcart.com/image/832/832/xif0q/wallet-card-wallet/l/4/y/-original-imagggj9dpdzcseu.jpeg?q=70",
    img4:"https://rukminim1.flixcart.com/image/832/832/xif0q/wallet-card-wallet/j/n/t/-original-imagnvuxexycvzw7.jpeg?q=70",

    alt: "Product Image 5",
    product: "Purse",
    price: "₹1,359",
    desc: "Clutch bag purse",
    category:"fashion",
    prod_info:"Women Yellow Artificial Leather Wallet - Regular Size  (9 Card Slots)",
  },
];

export default ProductList;