const ProductList = [
  {
    id:1,
    src: "https://m.media-amazon.com/images/I/41IcuNkyrdL._SX300_SY300_QL70_FMwebp_.jpg",
    alt: "Product Image 1",
    product: "Mobile",
    price: "$300",
    desc: "Samsung M04",
    category:"electronics",
  },
  {
    id:2,
    src: "https://m.media-amazon.com/images/I/718XDEWTPIL._UL1500_.jpg",
    alt: "Product Image 2",
    product: "Watch",
    price: "$120",
    desc: "Redux Watch",
    category:"electronics",
  },
  {
    id:3,
    src: "https://m.media-amazon.com/images/I/51UhwaQXCpL._SX679_.jpg",
    alt: "Product Image 3",
    product: "Earphones",
    price: "$70",
    desc: "Boat earphones",
    category:"electronics",
  },
  {
    id:4,
    src: "https://m.media-amazon.com/images/I/51tS-cfYoXL._SX679_.jpg",
    alt: "Product Image 4",
    product: "Charger",
    price: "$50",
    desc: "Apple charger",
    category:"electronics",
    
  },
  {
    id:5,
    src: "https://m.media-amazon.com/images/I/51sZaNaWzZL._SX300_SY300_QL70_FMwebp_.jpg",
    alt: "Product Image 5",
    product: "Laptop",
    price: "$1000",
    desc: "HP Laptop",
    category:"electronics",
  },
  {
    id:6,
    src: "https://m.media-amazon.com/images/I/81WtQ64-SOL._SX522_.jpg",
    alt: "Product Image 6",
    product: "Camera",
    price: "$500",
    desc: "Nikon Camera",
    category:"electronics",
  },
  {
    id:7,
    src: "https://m.media-amazon.com/images/I/71S-WpFnW+L._SL1500_.jpg",
    alt: "Product Image 7",
    product: "TV",
    price: "$500",
    desc: "Television",
    category:"electronics",
  },
  {
    id:8,
    src: "https://m.media-amazon.com/images/I/71GU85VOpnL._SX522_.jpg",
    alt: "Product Image 8",
    product: "Projector",
    price: "$500",
    desc: "Projector",
    category:"electronics",
  },
  {
    id:9,
    src: "https://m.media-amazon.com/images/I/31NVItwqOnL._SX300_SY300_QL70_FMwebp_.jpg",
    alt: "Product Image 9",
    product: "Printer",
    price: "$500",
    desc: "Hourse Hold Printer",
    category:"electronics",
  },
  {
    id:10,
    src: "https://m.media-amazon.com/images/I/51GyUUKe-0L._AC_UL320_.jpg",
    alt: "Product Image 1",
    product: "Oil",
    price: "Rs 139",
    desc: "Fortiune oil",
    category:"grocery",
  },
  {
    id:11,
    src: "https://m.media-amazon.com/images/I/91eEvcDs51L._AC_UL320_.jpg",
    alt: "Product Image 2",
    product: "Pulses",
    price: "Rs 245",
    desc: "Moong Dal",
    category:"grocery",
  },
  {
    id:12,
    src: "https://m.media-amazon.com/images/I/81+FF+RsymL._AC_UL320_.jpg",
    alt: "Product Image 3",
    product: "Atta",
    price: "Rs 300",
    desc: "Ashirvad Atta",
    category:"grocery",
  },
  {
    id:13,
    src: "https://m.media-amazon.com/images/I/81Xzx5PHTFL._AC_UL320_.jpg",
    alt: "Product Image 4",
    product: "Maggie",
    price: "Rs 20",
    desc: "Maggie Noodels",
    category:"grocery",
  },
  {
    id:14,
    src: "https://m.media-amazon.com/images/I/814iBcUf1aL._AC_UL320_.jpg",
    alt: "Product Image 5",
    product: "Cookies",
    price: "Rs 225",
    desc: "Unibic Cookies",
    category:"grocery",
  },
  {
    id:15,
    src: "https://m.media-amazon.com/images/I/71foBxdA7tL._AC_UL320_.jpg",
    alt: "Product Image 6",
    product: "BournVita",
    price: "Rs 500",
    desc: "Health Drink",
    category:"grocery",
  },
  {
    id:16,
    src: "https://m.media-amazon.com/images/I/81hqKpscwCL._AC_UL320_.jpg",
    alt: "Product Image 7",
    product: "Fruits",
    price: "Rs 100",
    desc: "Grapes",
    category:"grocery",
  },
  {
    id:17,
    src: "https://m.media-amazon.com/images/I/71MekfPhKNL._AC_UL320_.jpg",
    alt: "Product Image 8",
    product: "Honey",
    price: "Rs 600",
    desc: "Dabur honey",
    category:"grocery",
  },
  {
    id:18,
    src: "https://m.media-amazon.com/images/I/61SpB8J3HqL._AC_UL320_.jpg",
    alt: "Product Image 9",
    product: "Toothpaste",
    price: "Rs 50",
    desc: "Colgate Maxfresh",
    category:"grocery",
  },
  {
    id:19,
    src: "https://m.media-amazon.com/images/I/71ephbjp7FL._AC_UL320_.jpg",
    alt: "Product Image 1",
    product: "Shoe Rack",
    price: "Rs 711",
    desc: "KSP metal shoe rack",
    category:"home",
  },
  {
    id:20,
    src: "https://m.media-amazon.com/images/I/81SOycLGtdL._AC_UL320_.jpg",
    alt: "Product Image 2",
    product: "Mat",
    price: "Rs 340",
    desc: "Door mat",
    category:"home",
  },
  {
    id:21,
    src: "https://m.media-amazon.com/images/I/71pG4CvrxvL._AC_UL320_.jpg",
    alt: "Product Image 3",
    product: "Chopper",
    price: "Rs 600",
    desc: "Vegetable chopper",
    category:"home",
  },
  {
    id:22,
    src: "https://m.media-amazon.com/images/I/81ml0s5AHZL._AC_UL320_.jpg",
    alt: "Product Image 4",
    product: "Home Temple",
    price: "Rs 2000",
    desc: "Wooden puja stand",
    category:"home",
  },
  {
    id:23,
    src: "https://m.media-amazon.com/images/I/71QjQZ-nZCL._AC_UL320_.jpg",
    alt: "Product Image 5",
    product: "Lunch box",
    price: "$1000",
    desc: "HP Laptop",
    category:"home",
  },
  {
    id:24,
    src: "https://m.media-amazon.com/images/I/61c6L8Y-0aL._AC_UL320_.jpg",
    alt: "Product Image 6",
    product: "Fan",
    price: "$500",
    desc: "Exhaust fan for kitchen",
    category:"home",
  },
  {
    id:25,
    src: "https://m.media-amazon.com/images/I/61SzlTQhA4L._AC_UL320_.jpg",
    alt: "Product Image 7",
    product: "Bedsheet",
    price: "Rs 500",
    desc: "BSB Cotton Bedsheet",
    category:"home",
  },
  {
    id:26,
    src: "https://m.media-amazon.com/images/I/61r+cjuG37L._AC_UL320_.jpg",
    alt: "Product Image 8",
    product: "Freshener",
    price: "Rs 100",
    desc: "Godrej aer freshener",
    category:"home",
  },
  {
    id:27,
    src: "https://m.media-amazon.com/images/I/314lsfI3d8L._AC_UL320_.jpg",
    alt: "Product Image 9",
    product: "Furniture",
    price: "$500",
    desc: "Seater home sofa",
    category:"home",
  },
  {
    id:28,
    src: "https://m.media-amazon.com/images/I/81uL5oJmQxL._AC_UY218_.jpg",
    alt: "Product Image 1",
    product: "Vocabulary",
    price: "Rs 280",
    desc: "English vocabulary",
    category:"books",
  },
  {
    id:29,
    src: "https://m.media-amazon.com/images/I/71xWWxjzF7L._AC_UY218_.jpg",
    alt: "Product Image 2",
    product: "Mythology",
    price: "Rs 200",
    desc: "Story books for kids",
    category:"books",
  },
  {
    id:30,
    src: "https://m.media-amazon.com/images/I/81gTwYAhU7L._AC_UY218_.jpg",
    alt: "Product Image 3",
    product: "Motivational ",
    price: "Rs 500",
    desc: "Subconcious Mind",
    category:"books",
  },
  {
    id:31,
    src: "https://m.media-amazon.com/images/I/7175YpTSa7L._AC_UY218_.jpg",
    alt: "Product Image 4",
    product: "Kids",
    price: "100",
    desc: "brain activity",
    category:"books",
  },
  {
    id:32,
    src: "https://m.media-amazon.com/images/I/71SkkYOAaLL._AC_UY218_.jpg",
    alt: "Product Image 5",
    product: "Stock Market",
    price: "Rs 500",
    desc: "Price action trading",
    category:"books",
  },
  {
    id:33,
    src: "https://m.media-amazon.com/images/I/71U0g18pxyS._AC_UY218_.jpg",
    alt: "Product Image 6",
    product: "Poems",
    price: "Rs 300",
    desc: "50 greatest poems",
    category:"books",
  },
  {
    id:34,
    src: "https://m.media-amazon.com/images/I/819n0tHLQAL._AC_UY218_.jpg",
    alt: "Product Image 7",
    product: "Horror",
    price: "Rs 1000",
    desc: "Horror Stories",
    category:"books",
  },
  {
    id:35,
    src: "https://m.media-amazon.com/images/I/71KM8qTSbUL._AC_UY218_.jpg",
    alt: "Product Image 8",
    product: "Pregancy",
    price: "Rs 400",
    desc: "Belly to Baby",
    category:"books",
  },
  {
    id:36,
    src: "https://m.media-amazon.com/images/I/41n1edvVlLL._AC_UY218_.jpg",
    alt: "Product Image 9",
    product: "Biography",
    price: "Rs 360",
    desc: "Steve Jobs",
    category:"books",
  },

  {
    id:37,
    src: "https://m.media-amazon.com/images/I/71gAlld6UHL._AC_UL320_.jpg",
    alt: "Product Image 1",
    product: "Women Top",
    price: "Rs 550",
    desc: "Casual top",
    category:"fashion",
  },
  {
    id:38,
    src: "https://m.media-amazon.com/images/I/711ou4xAFTL._AC_UL320_.jpg",
    alt: "Product Image 2",
    product: "Footwear",
    price: "Rs 300",
    desc: "Summer sandal",
    category:"fashion",
  },
  {
    id:39,
    src: "https://m.media-amazon.com/images/I/51wEC1CRZtL._AC_UL320_.jpg",
    alt: "Product Image 3",
    product: "Bags",
    price: "rs 600",
    desc: "Shoulder bags",
    category:"fashion",
  },
  {
    id:40,
    src: "https://m.media-amazon.com/images/I/71a7hU2E6tL._AC_UL320_.jpg",
    alt: "Product Image 4",
    product: "Women's Set",
    price: "Rs 1500",
    desc: "Floral top with Pyjama",
    category:"fashion",
  },
  {
    id:41,
    src: "https://m.media-amazon.com/images/I/71cnAWrBHXL._AC_UL320_.jpg",
    alt: "Product Image 5",
    product: "Jacket",
    price: "Rs 499",
    desc: "Men's denim jacket",
    category:"fashion",
  },
  {
    id:42,
    src: "https://m.media-amazon.com/images/I/41tFff4qC6L._AC_UL320_.jpg",
    alt: "Product Image 6",
    product: "Sadi",
    price: "Rs 1500",
    desc: "Silk embroider work",
    category:"fashion",
  },
  {
    id:43,
    src: "https://m.media-amazon.com/images/I/71bfPnNplmL._AC_UL320_.jpg",
    alt: "Product Image 7",
    product: "Wallet",
    price: "$500",
    desc: "Brown leather wallet",
    category:"fashion",
  },
  {
    id:44,
    src: "https://m.media-amazon.com/images/I/616NVTS05CL._AC_UL320_.jpg",
    alt: "Product Image 8",
    product: "Jewellery",
    price: "Rs 480",
    desc: "Solid silver chain",
    category:"fashion",
  },
  {

    id:45,

    src: "https://m.media-amazon.com/images/I/71irYwattwL._AC_UL320_.jpg",
    alt: "Product Image 5",
    product: "Purse",
    price: "Rs 299",
    desc: "Clutch bag purse",
    category:"fashion",
  },
];

export default ProductList;